# Generated by Django 2.2.14 on 2021-09-25 02:07

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(blank=True, max_length=1000, null=True)),
                ('lastname', models.TextField(blank=True, max_length=1000, null=True)),
                ('email', models.TextField(blank=True, max_length=1000, null=True)),
                ('phonenumber', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=12, null=True)),
                ('city', models.TextField(blank=True, max_length=20, null=True)),
                ('state', models.TextField(blank=True, max_length=20, null=True)),
                ('zipcode', models.TextField(blank=True, max_length=8, null=True)),
                ('Gender', models.TextField(blank=True, max_length=1000, null=True)),
                ('Married', models.TextField(blank=True, max_length=1000, null=True)),
                ('Dependents', models.IntegerField(blank=True, null=True)),
                ('Education', models.TextField(blank=True, max_length=1000, null=True)),
                ('Self_Employed', models.TextField(blank=True, max_length=1000, null=True)),
                ('ApplicantIncome', models.IntegerField(blank=True, null=True)),
                ('CoapplicantIncome', models.IntegerField(blank=True, null=True)),
                ('LoanAmount', models.IntegerField(blank=True, null=True)),
                ('Loan_Amount_Term', models.IntegerField(blank=True, null=True)),
                ('Credit_History', models.TextField(blank=True, max_length=1000, null=True)),
                ('Property_Area', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationForLoan',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobile_no', models.IntegerField(blank=True, null=True)),
            ],
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
