# Generated by Django 2.2.14 on 2021-10-09 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoanProcessingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegUserLoanCheckDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.TextField(blank=True, max_length=10, null=True)),
                ('Married', models.TextField(blank=True, max_length=10, null=True)),
                ('Dependents', models.CharField(blank=True, max_length=3, null=True)),
                ('Education', models.TextField(blank=True, max_length=25, null=True)),
                ('Self_Employed', models.TextField(blank=True, max_length=3, null=True)),
                ('ApplicantIncome', models.IntegerField(blank=True, null=True)),
                ('CoapplicantIncome', models.IntegerField(blank=True, null=True)),
                ('LoanAmount', models.IntegerField(blank=True, null=True)),
                ('Loan_Amount_Term_In_Months', models.IntegerField(blank=True, null=True)),
                ('Credit_History', models.TextField(blank=True, max_length=15, null=True)),
                ('Property_Area', models.TextField(blank=True, max_length=10, null=True)),
                ('registeredUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoanProcessingApp.RegistrationForLoan')),
            ],
        ),
    ]
