# Generated by Django 2.2.14 on 2021-10-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanProcessingApp', '0003_reguserloancheckdetails_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguserloancheckdetails',
            name='Result',
            field=models.IntegerField(default=False),
        ),
    ]
