# Generated by Django 2.2.14 on 2021-10-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanProcessingApp', '0004_auto_20211008_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguserloancheckdetails',
            name='Result',
            field=models.TextField(default=False, max_length=15),
        ),
    ]
