# Generated by Django 2.2.14 on 2021-10-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanProcessingApp', '0005_auto_20211008_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationforloan',
            name='isPrimeMember',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
