# Generated by Django 2.2.14 on 2021-10-16 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanProcessingApp', '0006_registrationforloan_isprimemember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationforloan',
            old_name='isPrimeMember',
            new_name='isPremiumMember',
        ),
    ]
