# Generated by Django 2.2.14 on 2021-10-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanProcessingApp', '0007_auto_20211015_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationforloan',
            name='card_month',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registrationforloan',
            name='card_number',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registrationforloan',
            name='card_year',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registrationforloan',
            name='name_on_card',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
