# Generated by Django 2.2.14 on 2021-10-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanProcessingApp', '0008_auto_20211015_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationforloan',
            name='card_cvv',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
