# Generated by Django 2.2.14 on 2021-10-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanProcessingApp', '0009_registrationforloan_card_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationforloan',
            name='premium_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
