# Generated by Django 2.2.14 on 2021-10-20 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoanProcessingApp', '0010_registrationforloan_premium_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationforloan',
            name='card_cvv',
        ),
        migrations.RemoveField(
            model_name='registrationforloan',
            name='card_month',
        ),
        migrations.RemoveField(
            model_name='registrationforloan',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='registrationforloan',
            name='card_year',
        ),
        migrations.RemoveField(
            model_name='registrationforloan',
            name='name_on_card',
        ),
        migrations.RemoveField(
            model_name='registrationforloan',
            name='premium_amount',
        ),
        migrations.CreateModel(
            name='PremiumPaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_amount', models.IntegerField(blank=True, null=True)),
                ('name_on_card', models.TextField(blank=True, max_length=50, null=True)),
                ('card_number', models.BigIntegerField(blank=True, null=True)),
                ('card_month', models.TextField(blank=True, max_length=50, null=True)),
                ('card_year', models.TextField(blank=True, max_length=50, null=True)),
                ('card_cvv', models.IntegerField(blank=True, null=True)),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoanProcessingApp.RegistrationForLoan')),
            ],
        ),
    ]
